name: .NET

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # Измените с ubuntu-latest на windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x  # Убедитесь, что версия SDK соответствует вашей целевой версии
    - name: Restore dependencies
      run: dotnet restore ./ProjectTwo/ProjectTwo.sln
    - name: Build
      run: dotnet build --no-restore ./ProjectTwo/ProjectTwo.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./ProjectTwo/ProjectTwo.sln
